on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  source:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code #Get source code
        uses: actions/checkout@v4
      
      - name: Upload the code
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          retention-days: 1
  
  build:
    needs: source
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: code
      
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Set up python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
            
      - name: Install npm and run build
        run: |
          cd ./frontend
          npm install
          npm run build
          rm -rf node_modules

      - name: Upload the code
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      artifact-url: ${{ steps.upload-test-report.outputs.artifact-url }}
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: Set up python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-   

      - name: Run tests
        run: |
            source .venv/bin/activate
            pytest tests/ --html-report=./report/report.html 
      
      - name: Upload test report
        id: upload-test-report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ./backend/report